site_name: CodeFusion Studio
copyright: Copyright &copy; 2024-2025 Analog Devices Inc. All Rights Reserved.
site_url: https://developer.analog.com/docs/codefusion-studio
site_description: CodeFusion Studio is a powerful, easy-to-use development environment for Analog Devices' microcontrollers.

theme:
  name: harmonic
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tooltips
    - content.code.copy

extra:
  version:
    provider: mike

extra_css:
  - assets/templates/pdf_overrides.css

plugins:
  - glightbox
  - material/search
  - print-site:
      enabled: !ENV [ENABLE_PDF_EXPORT, false]
      add_cover_page: true
      enumerate_headings: false
      print_page_title: CodeFusion Studio
      cover_page_template: "docs/assets/templates/cover_page.tpl"
  - mike:
      alias_type: copy


nav:
  - User Guide:
    - user-guide/index.md
    - About:
      - user-guide/about/index.md
      - Purpose: user-guide/about/purpose.md
      - Features: user-guide/about/features.md
      - Navigation: user-guide/about/navigation.md
      - Supported processors: user-guide/about/supported-processors.md
      - Help: user-guide/about/help.md
    - Installation:
      - user-guide/installation/index.md
      - Requirements: user-guide/installation/software-requirements.md
      - Install CFS: user-guide/installation/install-cfs.md
      - Set up CFS: user-guide/installation/set-up-cfs.md
      - Manually install the VS Code extension: user-guide/installation/install-extensions.md
      - Install Olimex JTAG drivers: user-guide/installation/install-olimex-drivers.md
      - Install Segger J-Link drivers: user-guide/installation/install-jlink-drivers.md
    - Workspace Management:
      - user-guide/workspaces/index.md
      - Create a new workspace: user-guide/workspaces/create-new-workspace.md
      - Open a workspace: user-guide/workspaces/open-workspace.md
      - Open and migrate example: user-guide/workspaces/open-and-migrate-example.md
      - Migrate a project to System Planner: user-guide/workspaces/migrate-project-to-system-planner.md
      - CFS settings: user-guide/workspaces/cfs-settings.md
      - Catalog Manager: user-guide/workspaces/catalog-manager.md
      - Tasks: user-guide/workspaces/tasks.md
      - The CFS Terminal: user-guide/workspaces/cfs-terminal.md
      - Zephyr RTOS: user-guide/workspaces/zephyr.md
      - Troubleshooting: user-guide/workspaces/troubleshooting.md
    - Debugging:
      - user-guide/debugging/index.md
      - Debug an application: user-guide/debugging/debug-an-application.md
      - Debugging a multicore application: user-guide/debugging/debug-multi-core-application.md
      - Troubleshooting: user-guide/debugging/troubleshooting.md
    - Tools:
      - user-guide/tools/index.md
      - System Planner:
        - user-guide/tools/config-tool/index.md
        - Peripheral Allocation: user-guide/tools/config-tool/peripheral-allocation.md
        - Pin Config: user-guide/tools/config-tool/pin-config.md
        - Clock Config: user-guide/tools/config-tool/clock-config.md
        - Memory Allocation: user-guide/tools/config-tool/memory-allocation.md
        - Registers: user-guide/tools/config-tool/registers.md
        - Generate Code: user-guide/tools/config-tool/generate-code.md
      - CFS Command Line Utility: user-guide/tools/cfsutil.md
      - ELF File Explorer: user-guide/tools/elf-file-explorer.md
      - Device Tree View: user-guide/tools/device-tree-view.md
    - Plugins:
      - user-guide/plugins/index.md
      - Plugins overview: user-guide/plugins/plugin-integration-overview.md
      - Develop plugins: user-guide/plugins/develop-plugins.md
    - Uninstall:
      - Uninstalling CodeFusion Studio: user-guide/uninstall/uninstall-cfs.md
  - Tutorials:
    - tutorials/index.md
    - GDB Tutorial:
      - tutorials/gdb-tutorial/index.md
      - GDB Basics: tutorials/gdb-tutorial/gdb-basics.md
      - GDB Commands: tutorials/gdb-tutorial/gdb-commands.md
  - Resources:
    - user-guide/resources/index.md
    - SDKs: user-guide/resources/sdk-resources.md
    - Security: user-guide/resources/security-resources.md
    - Third-party: user-guide/resources/third-party-resources.md
  - Release Notes:
    - release-notes/index.md
    - 1.1.0: release-notes/1.1.0.md
    - 1.0.2: release-notes/1.0.2.md
    - 1.0.0: release-notes/1.0.0.md

not_in_nav: |
  glossary.md
  index.md
  walkthrough

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - docs/glossary.md
  - pymdownx.details
  - pymdownx.superfences
